## Problem statement

Given a list of training set of purchase history from social media ad, age of a person and income. Come up with a  model give the age and income predeict if he/she will purchase a product based on social media ad

In [1]:
import numpy as np
import pandas as pd


In [13]:
def load_data():
    data = pd.read_csv("Social_Network_Ads.csv")
    #print(data)
    X = data.iloc[:,:-1].values ## Give out put as ndarry
    Y = data.iloc[:,-1].values
    #print(X)
    #print(Y)
    return X,Y
                       

In [14]:
X,Y = load_data()

In [17]:
Y[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [18]:
## As the features are very divergent do feature scaling
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()
X = scalar.fit_transform(X)
print(X)

[[-1.78179743 -1.49004624]
 [-0.25358736 -1.46068138]
 [-1.11320552 -0.78528968]
 [-1.01769239 -0.37418169]
 [-1.78179743  0.18375059]
 [-1.01769239 -0.34481683]
 [-1.01769239  0.41866944]
 [-0.54012675  2.35674998]
 [-1.20871865 -1.07893824]
 [-0.25358736 -0.13926283]
 [-1.11320552  0.30121002]
 [-1.11320552 -0.52100597]
 [-1.6862843   0.47739916]
 [-0.54012675 -1.51941109]
 [-1.87731056  0.35993973]
 [-0.82666613  0.30121002]
 [ 0.89257019 -1.3138571 ]
 [ 0.70154394 -1.28449224]
 [ 0.79705706 -1.22576253]
 [ 0.98808332 -1.19639767]
 [ 0.70154394 -1.40195167]
 [ 0.89257019 -0.60910054]
 [ 0.98808332 -0.84401939]
 [ 0.70154394 -1.40195167]
 [ 0.79705706 -1.37258681]
 [ 0.89257019 -1.46068138]
 [ 1.08359645 -1.22576253]
 [ 0.89257019 -1.16703281]
 [-0.82666613 -0.78528968]
 [-0.63563988 -1.51941109]
 [-0.63563988  0.12502088]
 [-1.01769239  1.97500684]
 [-1.59077117 -1.5781408 ]
 [-0.92217926 -0.75592482]
 [-1.01769239  0.59485858]
 [-0.25358736 -1.25512738]
 [-0.44461362 -1.22576253]
 

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=0, test_size=1/3)

In [20]:
## Split data into train and test set
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, Y_train)


LogisticRegression()

In [21]:
## Predict result 
Y_pred = log_reg.predict(X_test)
        

In [27]:
result = np.concatenate((Y_test.reshape(-1,1), Y_pred.reshape(-1,1)),1)
#print(result)

In [28]:
log_reg.score(X_test,Y_test)

0.8731343283582089

In [29]:
## Getting the confusion matrix and accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score

confusion_matrix(Y_test,Y_pred)

array([[79,  6],
       [11, 38]], dtype=int64)

In [31]:
## print accurary score - Same as log_reg.score
accuracy_score(Y_test, Y_pred)

0.8731343283582089